### ISSUE TITLE
`position: relative` doesnt play nice with fixed banner-position

### ISSUE THREAD

**Issue by 5shekel** [Balancingrock/classic-jekyll-theme#16]
if I set in setup.yml
```banner-position: top-fixed```
and use
```{%- include widgets/youtube-player.html video='Identifier of the video' -%}```
in a _post, it will not scroll below the fixed-banner as expected, but above.

if i remove ```position: relative``` from  _sass/_widget this fixes it.

**Comment by Balancingrock** [comment]
Thanks, that is indeed a reproducible problem.

However the fix you propose does not work for the standard files in the theme. Removing the 'position: relative' will only make the video expand to occupy the entire screen.

I will take a look at this.

**Comment by 5shekel** [comment]
here is my modified fork, if it helps
https://github.com/shenkarSElab/IDIOT.io

**Comment by Balancingrock** [comment]
I have spend a couple of hours on this, and I cannot identify a suitable solution.

Setting a z-index of -1 on the iframe does work in the sense that the video will now scroll below the fixed banner, but it also disables the drop-down menu hover effect. Effectively disabling the menu when the video is wide enough and under the banner (potentially even invisible).

Flash has indeed a known problem and the solutions offered is setting the `wmode` to `opaque`. However this seems to make no difference at all. It neither makes the z-index setting superfluous, nor does it fix the failing hover effect.

As it is, I will probably add the z-index setting and recommend not using the drop-down menu if a top-fixed banner is used.

**Comment by 5shekel** [comment]
wonder why this hack works on my theme. 

thanks for the effort spent on this

i also had this overlap issue with an image-resize class I added to _sass/_customs.sass
same fix.

**Comment by Balancingrock** [comment]
Well, this requires some explanation...

In your site you include video's directly by coding the iframe, you do not use the youtube-player widget. And hence the settings for the widget do not affect your site.

The reason for the widget is to create a auto-scaling wrapper for the iframe that will fill out the entire width of a column, yet keep the HD aspect ratio.

Unfortunately the widget needs to use a trick to keep the aspect ratio constant, which needs 'position: absolute'. But using this positioning, the player is elevated out of the DOM and thus will float above the page it is in. Since the position and size of the player are kept synchronous with the position of its container, this works fine.... until scrolling puts the video 'behind' the banner. The banner is also placed outside the DOM, but the video player takes priority and is placed above the banner. Which results in the video seeming to float over the banner/menu.

The z-index solution does not work either since this causes the container of the iframe to be placed in front of the player, intercepting the mouse events. hence the player cannot be used anymore. Using 'pointer-event:none' on the container does not work either for reasons as of yet unclear to me.

So we are left with the only alternative: when using top-fixed for the banner-menu, do not use the youtube-player widget but use the iframe directly like you did on your site. (And lose the auto-scaling)
