### ISSUE TITLE
Using remote absolute 'url' as menu item prepends local site

### ISSUE THREAD

**Issue by dcrossleyau** [Balancingrock/classic-jekyll-theme#20]
When using a remote url as a menu item, the resultant link has the local site pre-pended.

```
$ diff 05-menus.md.orig 05-menus.md
10a11,17
> - title: Test menu remote url 1
>   url: https://github.com/Balancingrock/classic-jekyll-theme
>   index: 10
> - title: Test menu remote url 2
>   url: http://www.balancingrock.nl/classic-jekyll-theme/pages/classic/04-menus.html
>   index: 11
>   anchorId: frontmatter
```

That yields:
`http://127.0.0.1:5001/https://github.com/Balancingrock/classic-jekyll-theme`
etc.

The [Menus in Classic](http://www.balancingrock.nl/classic-jekyll-theme/pages/classic/04-menus.html#frontmatter) documentation page does say that this is possible.

(By the way, the demo site is out-of-date.)

**Comment by Balancingrock** [comment]
Ah yes, this is caused by the using the 'relative_url' moniker. This was introduced to allow sites to be hosted at something other than the top level domain. E.g. `mysite.com/subpath/index.html`
I would like to keep that feature, but it is also wrong to apply it to the URL's that start with `http`.

This will be fixed asap.

**Comment by Balancingrock** [comment]
Issue should be fixed in HEAD.

I also found two warnings on the 'About menus' page which no longer apply, I have removed them.

**Comment by dcrossleyau** [comment]
Thanks. That is a nice ability.

Thanks too to "remote-jekyll-theme" which enabled us to quickly apply your fix.
